### ISSUE TITLE
Optimize loop

### ISSUE THREAD

**Issue by lpatiny** [andrescvargasr/prime-js-number#2]
https://github.com/andrescvargasr/prime-js-number/blob/master/src/index.js#L21

The operation i*i has to be done each time.

I would rather do `i <= Math.sqrt(number)`

**Comment by andrescvargasr** [comment]
Solved in commit [d70ab50](https://github.com/andrescvargasr/prime-js-number/commit/d70ab504ea10c5c26e62ec5f8e15dc097e28dbd6)
