### ISSUE TITLE
jsDoc not correct

### ISSUE THREAD

**Issue by lpatiny** [andrescvargasr/prime-js-number#4]
We generate automatically the documentation from jsDoc and there should be only one block of comments above the function that describe the method, the input variables and the return.

**Comment by andrescvargasr** [comment]
Maybe this option [Line 4](https://github.com/andrescvargasr/prime-js-number/blob/55f533dbc624158d97fc63603c9e0dc46e56192a/src/index.js#L4)

**Comment by lpatiny** [comment]
Yes it looks ok. Normally we build automatically the documentation on github but you can also test it locally.

You can install globally the package documentation

`npm i --global documentation`

And then execute from command line in your project

`documentation build src/** -f html -o docs`

This will create a docs folder with the documentation.

You can also install in vscode the plugin 'live server' and then in this docs folder right click on index.html and 'open with live-server'. You should see the build documentation.

**Comment by andrescvargasr** [comment]
Thank you very much!
